version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: dotnet test --no-build --configuration Release -l trx -r /build/tests/xunit /p:CollectCoverage=true /p:Include=[ScrumToolbox.*]* /p:CoverletOutputFormat=opencover /p:CoverletOutput=/build/coverage/coverage.xml
      - run:
          name: Publish build
          command: dotnet publish  --no-build --configuration Release ./ScrumToolbox.WebApi/ScrumToolbox.WebApi.csproj
      - store_artifacts: 
          path: /build/ScrumToolbox.WebApi/bin/Release/netcoreapp2.1/publish
          destination: app-build
      - store_artifacts: 
          path: /build/coverage
          destination: code-coverage
      - store_test_results:
          path: /build/tests/xunit