version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:Include=[ScrumToolbox.*]* /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/coverage.xml
      - run: reportgenerator -reports:/coverage/coverage.xml -targetdir:./coverage/report
      - run: dotnet publish  --no-build --configuration Release ./ScrumToolbox.WebApi/ScrumToolbox.WebApi.csproj
      - store_artifacts: 
          path: /build/ScrumToolbox.WebApi/bin/Release/netcoreapp2.1/publish
          destination: app-build
      - store_artifacts: 
          path: /build/coverage/report
          destination: code-coverage