version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: |
            dotnet test \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=results.xml" \
            --results-directory /build/tests \
            /p:CollectCoverage=true \
            /p:Include=[ScrumToolbox.*]* \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=/build/coverage/coverage.xml
      - store_artifacts: 
          path: /build/coverage
          destination: code-coverage
      - store_artifacts:
          path: /build/tests
          destination: test-results