version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test --no-build --configuration Release
      - run: dotnet publish  --no-build --configuration Release ./ScrumToolbox.WebApi/ScrumToolbox.WebApi.csproj
      - store_artifacts: 
        path: /build/ScrumToolbox.WebApi/bin/Release/netcoreapp2.1/publish
        destination: app-build